-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS my_schema.departments
(
    dept_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    dept_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT departments_pkey PRIMARY KEY (dept_no)
);

CREATE TABLE IF NOT EXISTS my_schema.dept_emp
(
    emp_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    dept_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dept_emp_pkey PRIMARY KEY (emp_no, dept_no)
);

CREATE TABLE IF NOT EXISTS my_schema.employees
(
    emp_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    emp_title_id character varying(6) COLLATE pg_catalog."default" NOT NULL,
    birth_date date NOT NULL,
    first_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sex character varying(1) COLLATE pg_catalog."default" NOT NULL,
    hire_date date NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS my_schema.titles
(
    title_id character varying(6) COLLATE pg_catalog."default" NOT NULL,
    title character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT titles_pkey PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS my_schema.dept_manager
(
    dept_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    emp_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dept_manager_pkey PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS my_schema.salaries
(
    emp_no character varying(6) COLLATE pg_catalog."default" NOT NULL,
    salary integer NOT NULL,
    CONSTRAINT salaries_pkey PRIMARY KEY (emp_no)
);

ALTER TABLE IF EXISTS my_schema.dept_emp
    ADD CONSTRAINT dept_emp_dept_no FOREIGN KEY (dept_no)
    REFERENCES my_schema.departments (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS dept_emp_dept_no_idx
    ON my_schema.dept_emp(dept_no);


ALTER TABLE IF EXISTS my_schema.dept_emp
    ADD CONSTRAINT dept_emp_emp_no FOREIGN KEY (emp_no)
    REFERENCES my_schema.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS dept_emp_emp_no_idx
    ON my_schema.dept_emp(emp_no);


ALTER TABLE IF EXISTS my_schema.employees
    ADD CONSTRAINT employees_emp_title_id FOREIGN KEY (emp_title_id)
    REFERENCES my_schema.titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS my_schema.dept_manager
    ADD CONSTRAINT dept_manager_emp_no FOREIGN KEY (emp_no)
    REFERENCES my_schema.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS dept_manager_pkey
    ON my_schema.dept_manager(emp_no);


ALTER TABLE IF EXISTS my_schema.salaries
    ADD CONSTRAINT salaries_emp_no FOREIGN KEY (emp_no)
    REFERENCES my_schema.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS salaries_emp_no_idx
    ON my_schema.salaries(emp_no);

END;